var TSB = TSB || {};
TSB.Fields = {
  MasterID : { type : 'Number', unique: true, comment : 'Internal TSB Number for Project Participant' },
  CompetitionYear : { type : 'Number', format : 'YYYY', comment : 'TSB Financial Year in which Competition started' },
  ActivityCode : { type : 'Text', comment: 'Internal TSB Financial Code' },
  AreaCode : { type : 'Text', comment: 'Not of any informational value' },
  CompCallCode : { type : 'Text', comment : 'Internal TSB Competition identifierAdded as Competition Identifier' },
  Product : { type : 'Text', comment : 'TSB Product Types' },
  AreaName : { type : 'Text', comment : 'Not of any informational value' },
  AreaBudgetHolder : { type : 'Text', comment : 'Area of TSB with budget responsibility equivalent to Priority Theme on web site' },
  TeamBudgetHolder : { type : 'Text', comment : 'Team of TSB with budget responsibility' },
  TSBProjectNumber : { type : 'Number', comment : 'Project Number Unique to each Project' },
  TPNumber : { type : 'Number', comment : 'Internal TSB Number Legacy reference now used to store application number' },
  ParticipantName : { type : 'Text', comment : 'Project Participant Organisation Name', unique : true },
  IsActive : { type : 'Enum', values : ['Active', ''], comment : 'Flag of participant status set to Active when Participant is currently drawing down budget although remains Active when project closes. Otherwise Withdrawn from Project' },
  IsLead : { type : 'Text', comment : 'Participant Project Role Indicates if Projec t Participant is / was either the Lead on the Project or Collaborator' },
  ProjectTitle : { type : 'Text', comment : 'Name of the Project', unique : true },
  ProjectStatus : { type : 'Enum', values : 'Closed,Final Claim due, Terminated, Live, On Hold, Deleted, Offer letter Sent' },
  StartDate : { type : 'Date', format: 'dd/mm/yyyy', comment : 'Date Project Starts' },
  ProjectEndDate : { type : 'Date', format: 'dd/mm/yyyy', comment : 'Date Project Ends' },
  MOName : { type : 'Text', comment : 'Monitoring Officer Name Not to be published' },
  MLOName : { type : 'Text', comment : 'Deputy Name Not to be published' },
  ProjectSICSubclass : { type : 'Text', comment : 'Project SIC sub Class I.E. Manufacture of compressors Data quality questionable from 2 years ago,1,Added as Competition Identifier' },
  EconomicDriverName : { type : 'Text', comment : 'Type of Market Green, Healthy, Productive, Digital Data quality questionable from 2 years ago' },
  FundedBy : { type : 'Enum', values : ['Technology Strategy Board', ''], comment : 'Technology Strategy Board  or Unknown' },
  OfferCost : { type : 'Number', comment : 'Total Cost estimated by Participant' },
  OfferGrant : { type : 'Number', comment : 'TSB funding amount  offered to the Participant' },
  OfferRateOfGrant : { type : 'Number', comment : 'Percentage of Total cost offered to Participant as Grant can be calculated form Offer Grant / Offer Cost' },
  PaymentsToDate : { type : 'Number', comment : 'Amount of offered Grant paid to date' },
  CostCategoryType : { type : 'Text', comment : 'Industrial or Academic flag' },
  ParticipantType : { type : 'Text', comment : 'Participant Organisation size or Academic  duplicate of Enterprise size' },
  ParticipantOrganisationType : { type : 'Enum', values : [ 'Participant\'s Legal entity form',  'Limited', 'Higher education PLC', 'RTO' ] },
  EnterpriseSize : { type : 'Text', comment : 'Size of Participant Organisation based on EU classification or labeled Academic' },
  ParticipantSICSubclass : { type : 'Text', comment : 'SIC Code as reported to Companies House for the Participant' },
  CompanyRegNo : { type : 'Text', comment : 'Companies House Company Reg No.', unique : true },
  Region : { type : 'Text', comment : 'Regional Area entered by Participant Organisation' },
  MainContactName : { type : 'Text', comment : 'Contact name Not to be published' },
  MainContactEmail : { type : 'Text', format : 'email', comment : 'Contact E-Mail Not to be published' },
  MainContactPhone : { type : 'Text', format : 'Contact Phone Number Not to be published' },
  Address : { type : 'Text', comment : 'Address Line 1', unique : true },
  Town : { type : 'Text', comment : 'Address Line 2', unique : true },
  County : { type : 'Text', comment : 'Address Line 3', unique : true },
  Postcode : { type : 'Text', comment : 'Address Line 4', unique : true },
  SourcePartID : { type : 'Number', comment : 'Internal TSB Unique Participant Number' },
  UpdateProject : { type : 'Number', comment : 'Internal Program Flag' },
  UpdateParticipant : { type : 'Number', comment : 'Internal Program Flag' },
  ValidatedRegion : { type : 'Text', comment : 'Region based on postcode lookup' },
  Product : { type : '', comment : '' },
  AreaBudget : { type : '', comment : '' },
  TeamBudget : { type : '', comment : '' },
  EnterpriseSize : { type : '', comment : '' },
  FundersPanel : { type : 'Date', comment : 'Date on which TSB funders panel committed to the offer of grant' },
  PaymentToFy1213 : { type : '', comment : '' },
  OtherFields : { type : '', comment : 'No of FOI columns' },
  PublicDescription : { type : 'Text', comment : 'Textual details about project approved for publication', unique : true }
};